language: python
script: 
- pytest
- ./project.py
- ./project.py --xgb
- ./project.py --nn
- ./project.py --data "https://www.dropbox.com/s/v4sys56bqhmdfbd/fake.csv?dl=1" --xgb
- ./project.py --data "https://www.dropbox.com/s/v4sys56bqhmdfbd/fake.csv?dl=1" --nn
